import 'package:flutter/material.dart';

class DarkColors {
  const DarkColors._();
  static const Color seedColor = Color(0xff1e88e5);
  static const Color surface = Color(0xff111415);
  static const Color surfaceDim = Color(0xff111415);
  static const Color surfaceBright = Color(0xff222526);
  static const Color surfaceContainerLowest = Color.fromARGB(255, 44, 70, 92);
  static const Color surfaceContainerLow = Color(0xff191c1d);
  static const Color surfaceContainer = Color(0xff1d2021);
  static const Color surfaceContainerHigh = Color(0xff282a2b);
  static const Color surfaceContainerHighest = Color(0xff323536);
  static const Color onSurface = Color(0xffe1e3e4);
  static const Color onSurfaceVariant = Color(0xffc0c7d4);
  static const Color inverseSurface = Color(0xffe1e3e4);
  static const Color inverseOnSurface = Color(0xff2e3132);
  static const Color outline = Color(0xff747b85);
  static const Color outlineVariant = Color(0xff353b45);
  static const Color surfaceTint = Color(0xff9bc0ff);
  static const Color primary = Color(0xff9bc0ff);
  static const Color onPrimary = Color(0xff002e54);
  static const Color primaryContainer = Color(0xff004781);
  static const Color onPrimaryContainer = Color(0xffd1e4ff);
  static const Color inversePrimary = Color(0xff0060a8);
  static const Color secondary = Color(0xffb9c8da);
  static const Color onSecondary = Color(0xff233345);
  static const Color secondaryContainer = Color(0xff394b5d);
  static const Color onSecondaryContainer = Color(0xffd5e3f7);
  static const Color tertiary = Color(0xffd5b394);
  static const Color onTertiary = Color(0xff39220c);
  static const Color tertiaryContainer = Color(0xff523820);
  static const Color onTertiaryContainer = Color(0xfff3dfcf);
  static const Color error = Color(0xffffb4ab);
  static const Color onError = Color(0xff690005);
  static const Color errorContainer = Color(0xff93000a);
  static const Color onErrorContainer = Color(0xffdadada);
  static const Color primaryFixed = Color(0xffd3e4ff);
  static const Color primaryFixedDim = Color(0xffa2c9ff);
  static const Color onPrimaryFixed = Color(0xff001c38);
  static const Color onPrimaryFixedVariant = Color(0xff004881);
  static const Color secondaryFixed = Color(0xffd3e4ff);
  static const Color secondaryFixedDim = Color(0xffacc8f2);
  static const Color onSecondaryFixed = Color(0xff001c38);
  static const Color onSecondaryFixedVariant = Color(0xff2b486b);
  static const Color tertiaryFixed = Color(0xffffdcc4);
  static const Color tertiaryFixedDim = Color(0xffffb780);
  static const Color onTertiaryFixed = Color(0xff2f1400);
  static const Color onTertiaryFixedVariant = Color(0xff6f3800);
  static const Color background = Color(0xff111415);
  static const Color onBackground = Color(0xffe1e3e4);
  static const Color surfaceVariant = Color(0xff29313d);
}
